ZagrajZNami/ZagrajZNami/Controllers/SpotkanieController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZagrajZNami.App_Start;
using ZagrajZNami.DAL;
using ZagrajZNami.Infrastucture;
using ZagrajZNami.Models;
using ZagrajZNami.ViewModels;

namespace ZagrajZNami.Controllers
{
    [RequireHttps]
    public class SpotkanieController : Controller
    {
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                //Najpierw dodaæ Nuget For Solution -> Broswe -> Owin Host System web
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ZagrajZNamiContext db = new ZagrajZNamiContext();


        // GET: Spotkanie
        public ActionResult Index()
        {
           var spotkanie = db.Spotkania.ToList();
           return View(spotkanie);
        }

        // GET: Spotkanie
        public string Index2(string OpisSpotkania, string Cena)
        {
            //string qr = String.Format("select * from AspNetUsers where email='jakub4742@gmail.com' and PasswordHash='{0}'",password);
            //var user = db.Database.SqlQuery<ApplicationUser>(qry).ToList();
            var Spotkania =  db.Spotkania.SqlQuery("Select * from Spotkanie where OpisSpotkania = '" + OpisSpotkania +
                                                "' and Cena = " + Cena).ToList();

            if (Spotkania != null)
            {
                string s = "";
                foreach (var item in Spotkania)
                {
                    s += item.OpisSpotkania + item.Cena + "|";
                }
                return s;
            }
            else
            {
                return null;
            }
            //var adpt = new SqlDataAdapter(qry, con);

            //var  dt = new DataTable();

            //adpt.Fill(dt);

            //if (dt.Rows.Count >= 1)
            //{
            //    return adpt.ToString();
            //}
            //else
            //{
            //    return "Nic nie ma";
            //}
        }
    
        [HttpPost]
        public ActionResult Zaktualizuj(string nazwa)
        {
            var spotkania = db.Spotkania.ToList();

            if (nazwa == "DataW")
            {
                spotkania = spotkania.OrderByDescending(a => a.DataDodania).ToList();
                return View("_SpotkaniaList", spotkania);
            }

            else if (nazwa == "DataN")
            {
                spotkania = spotkania.OrderBy(a => a.DataDodania).ToList();
                return View("_SpotkaniaList", spotkania);
            }

            else if (nazwa == "CenaNajt")
            {
                spotkania = spotkania.OrderBy(a => a.Cena).ToList();
                return View("_SpotkaniaList", spotkania);
            }

            else if (nazwa == "CenaNajd")
            {
                spotkania = spotkania.OrderByDescending(a => a.Cena).ToList();
                return View("_SpotkaniaList", spotkania);
            }
            return null;
        }

    
        public ActionResult DodajSpotkanie()
        {
            //if(!User.Identity.IsAuthenticated)
            //{
            //    string infoS = "przed dodaniem spotkania proszę się zalogować";
            //    return RedirectToAction("Login", "Account", new { info = infoS });
            //}

            var vm = new SpotkanieObiektViewModels()
            {
                ObiektSportowy = new ObiektSportowy(),
                Spotkanie = new Spotkanie()
            };

            var spotkanie = new Spotkanie();
            var listaSpotkan = db.Spotkania.ToList();
            var obiektySportowe = db.ObiektySportowe.ToList();

            //Zrob cache
            List<ObiektSportowy> WszystkieObiekty;
            ICacheProvider cache = new DefaultCacheProvider();

            if (cache.IsSet(Consts.SpotkaniaCache))
            {
                WszystkieObiekty = cache.Get(Consts.SpotkaniaCache) as List<ObiektSportowy>;
            }
            else
            {
                WszystkieObiekty = db.ObiektySportowe.ToList();
                //Ustaw na cały dzień bo admin bedzie aktualizował te obiekty co dzień
                cache.Set(Consts.SpotkaniaCache, WszystkieObiekty, 1440);
            }

            List<string> obiektyOb = new List<string>();
            obiektySportowe.ForEach(a =>
            {
                if (!a.Nazwa.Equals(String.Empty))
                    obiektyOb.Add(a.Nazwa);
            });

            ViewBag.NazwyObiektow = obiektyOb.Distinct();
            return View(vm);
        }

        [HttpPost]
        public ActionResult UsunZSpotkania(int spotkanieID = -1, string userID = null)
        {
            ApplicationUser user;
            List<Spotkanie> spotkania;

            if (userID != null)
            {
                user = db.Users.Where(a => a.Email == userID).FirstOrDefault();
                spotkania = db.Spotkania.Where(a => a.UserId == user.Id).ToList();
            }
            else
            {
                userID = User.Identity.GetUserId();
                spotkania = db.Spotkania.ToList();
                user = db.Users.Find(userID);
            }

            user.Spotkania.Remove(db.Spotkania.First(a => a.SpotkanieID == spotkanieID));
            db.Spotkania.Find(spotkanieID).ApplicationUsers.Remove(db.Users.Find(userID));
            if(db.Spotkania.Find(spotkanieID).LiczbaMiejscZajetych > 0)
                db.Spotkania.Find(spotkanieID).LiczbaMiejscZajetych--;
            db.SaveChanges();

            return View("_SpotkaniaList", spotkania);

        }

        [ValidateAntiForgeryToken]
        public ActionResult DolaczDoSpotkania(Spotkanie obiekt, string userId = null)
        {
            var user = UserManager.FindById(userId);

            if (!user.Spotkania.Any(a => a.SpotkanieID == obiekt.SpotkanieID))
            {
                db.Users.Find(userId).Spotkania.Add(db.Spotkania.First(a => a.SpotkanieID == obiekt.SpotkanieID));
                db.Spotkania.Find(obiekt.SpotkanieID).ApplicationUsers.Add(db.Users.Find(userId));
                db.Spotkania.Find(obiekt.SpotkanieID).LiczbaMiejscZajetych++;
                db.SaveChanges();
                var spotkania = db.Spotkania.ToList();
                return View("_SpotkaniaList", spotkania);
            }
            else
                return null;
           
        }


        [HttpPost]
        
        public ActionResult DodajSpotkanie(SpotkanieObiektViewModels vm)
        {
            //  var userID = User.Identity.GetUserId();
            var userID = "8ffa541d-42aa-44b6-a533-4799fcce6557";
            var listaSpotkan = db.Spotkania.ToList();
            var obiektySportowe = db.ObiektySportowe.ToList();
            ICacheProvider cache = new DefaultCacheProvider();

            //Zrob cache
            List<ObiektSportowy> WszystkieObiekty;

            if (cache.IsSet(Consts.SpotkaniaCache))
            {
                WszystkieObiekty = cache.Get(Consts.SpotkaniaCache) as List<ObiektSportowy>;
            }
            else
            {
                WszystkieObiekty = db.ObiektySportowe.ToList();
                //Ustaw na cały dzień bo admin bedzie aktualizował te obiekty co dzień
                cache.Set(Consts.SpotkaniaCache, WszystkieObiekty, 1440);
            }



            List<string> obiektyOb = new List<string>();
            obiektySportowe.ForEach(a =>
            {
                if (!a.Nazwa.Equals(String.Empty))
                    obiektyOb.Add(a.Nazwa);
            });

            ViewBag.NazwyObiektow = obiektyOb.Distinct();

            vm.Spotkanie.DataDodania = DateTime.Now;
            vm.Spotkanie.ObiektSportowyID = db.ObiektySportowe.Where(a => a.Nazwa == vm.ObiektSportowy.Nazwa).First().ObiektSportowyID;
            vm.Spotkanie.DataSpotkania = DateTime.Now;
            vm.Spotkanie.GlownyObrazek = "Obrazek5.jpg";
            vm.Spotkanie.UserId = userID;
            db.Spotkania.Add(vm.Spotkanie);
            db.SaveChanges();
            ViewBag.Dodano = "Poprawnie dodano spotkanie!";
            return RedirectToAction("DodajSpotkanie");
        }

    }
}

ZagrajZNami/ZagrajZNami/Views/Admin/Index.cshtml
@model List<ZagrajZNami.Models.Spotkanie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManageAdminLayout.cshtml";
}

<div class="container">
    @*<div class="btn-group" role="group"></div>
    <div class="btn-group">
        <button id="btnSortowanieCenyNajt" class="btn btn-primary" type="button">Najtansze</button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <div class="btn-group">
        <button id="btnSortowanieCenyNajd" class="btn btn-primary" type="button">Najdroższe</button>
        <div class="dropdown-menu"
             role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <div class="btn-group">
        <button id="btnSortowanieDatyN" class="btn btn-primary" type="button">Najstarsze</button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <div class="btn-group">
        <button id="btnSortowanieDatyW" class="btn btn-primary" type="button">Najnowsze</button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <hr />*@

    <div id="Spotk">
        @{ Html.RenderPartial("_SpotkaniaList");}
    </div>
</div>

@section Scripts
    {
    <script>

            function Usun(ele)
            {
                $ele = $(ele);
                $userID = $ele.closest('span').attr('id').split(' ');
                $spotkanieID = $ele.closest('span').attr('name').split(' ');

                console.log($userID);
                console.log($spotkanieID);

                $.ajax({
                    type: "POST",
                url: '@Url.Action("UsunZSpotkania", "Spotkanie")',
                    data: { spotkanieID: $spotkanieID, userID: $userID},
                success: function (data)
                {
                    console.log(data);
                    $('#Spotkania').replaceWith(data);
                }
                });
                return;
            }

        $(document).ready(function ()
        {
            $('#btnSortowanieDatyW').click(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Admin")",
                    data: { nazwa: "DataW" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotk').replaceWith(result);
                    }
                });
            });

            $('#btnSortowanieDatyN').click(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Admin")",
                    data: { nazwa: "DataN" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotk').replaceWith(result);
                    }
                });
            });



            $('#btnSortowanieCenyNajt').click(function ()
            {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Admin")",
                    data: { nazwa: "CenaNajt" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotk').replaceWith(result);
                    }
                });
            });

            $('#btnSortowanieCenyNajd').click(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Admin")",
                    data: { nazwa: "CenaNajd" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotk').replaceWith(result);
                    }
                });
            });
        });
    </script>

}

ZagrajZNami/ZagrajZNami/Views/Admin/Uzytkownicy.cshtml
@model List<ZagrajZNami.Models.ApplicationUser>

@{
    ViewBag.Title = "Uzytkownicy";
    Layout = "~/Views/Shared/_ManageAdminLayout.cshtml";
}
e   
<h1>Wpisz wartości w polu, a następnie kliknij w przycisk żeby zmienić wartości</h1>

<div class="container" style="background-image: url('../../Content/Obrazki/jonathan-petersson-210341-unsplash.jpg');background-size: cover;background-repeat: repeat-x;background-position: center;height: auto;width: auto;">
    @*<div class="btn-group" role="group"></div>
    <div class="btn-group">
        <button id="btnSortowanieCenyNajt" class="btn btn-primary" type="button">Najtansze</button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <div class="btn-group">
        <button id="btnSortowanieCenyNajd" class="btn btn-primary" type="button">Najdroższe</button>
        <div class="dropdown-menu"
             role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <div class="btn-group">
        <button id="btnSortowanieDatyN" class="btn btn-primary" type="button">Najstarsze</button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <div class="btn-group">
        <button id="btnSortowanieDatyW" class="btn btn-primary" type="button">Najnowsze</button>
        <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">First Item</a><a class="dropdown-item" role="presentation" href="#">Second Item</a><a class="dropdown-item" role="presentation" href="#">Third Item</a></div>
    </div>
    <hr />*@

    <div id="Users">
        @{ Html.RenderPartial("_UzytkownicyList");}
    </div>
</div>

@section Scripts
    {
    <script>

        function Usun(ele)
            {
                $ele = $(ele);
            $userID = $ele.attr('id');
            console.log($userID);

                $.ajax({
                    type: "POST",
                url: '@Url.Action("UsunUzytkownika", "Admin")',
                    data: {userID: $userID},
                success: function (data)
                {
                    console.log(data);
                    $('#Spotkania').replaceWith(data);
                }
                });
                return;
            }


        $(document).ready(function ()
        {
            $('#btnSortowanieDatyW').click(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Admin")",
                    data: { nazwa: "DataW" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotkania').replaceWith(result);
                    }
                });
            });

            $('#btnSortowanieDatyN').click(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Spotkanie")",
                    data: { nazwa: "DataN" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotkania').replaceWith(result);
                    }
                });
            });



            $('#btnSortowanieCenyNajt').click(function ()
            {
                alert('dsa');
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Spotkanie")",
                    data: { nazwa: "CenaNajt" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotkania').replaceWith(result);
                    }
                });
            });

            $('#btnSortowanieCenyNajd').click(function () {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Zaktualizuj", "Spotkanie")",
                    data: { nazwa: "CenaNajd" },
                    success: function (result) {
                        //TODO: jezeli p;usty to nie renderuj
                        console.log('Powinno zmienic');
                        $('#Spotkania').replaceWith(result);
                    }
                });
            });
        });
    </script>

}

ZagrajZNami/ZagrajZNami/Views/Admin/WyslijEmail.cshtml
@model ZagrajZNami.ViewModels.EmailViewModel

@{
    ViewBag.Title = "WyslijEmail";
}

@if(ViewBag.Info != null)
{
    <p class="text-success">@ViewBag.Info</p>
}

    <div style="margin-top: 150px;">
        @using (Html.BeginForm("WyslijEmail", "Admin", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(o => o.UserToSend.Email, "Maile:")
                @Html.DropDownListFor(m => m.UserToSend.Email, new SelectList(ViewBag.Mails), new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(o => o.Wiadomosc, "Treść")
                @Html.TextBoxFor(o => o.Wiadomosc, new { @class = "form-control" })
            </div>

            <button type="submit">Wyslij</button>
        }

    </div>

ZagrajZNami/ZagrajZNami/Views/Admin/_SpotkaniaList.cshtml
@model List<ZagrajZNami.Models.Spotkanie>
@using Microsoft.AspNet.Identity;

@{
    Layout = null;
}


<span>
    <h1> @ViewBag.Innfo</h1>
</span>

<div id="S" style="margin-top: 150px;">
    @foreach (var obiekt in Model)
    {
        <div class="row" id="@obiekt.SpotkanieID">
            <div class="col-5 col-md-7 mb-4">
                <div class="card h-100"><a href="#"><img class="img-fluid" src="http://placehold.it/600x300"></a></div>
            </div>
            <div class="col-5 col-md-5 mb-4">
                @using (Ajax.BeginForm("Spotkania", obiekt, new AjaxOptions
                {
                    HttpMethod = "POST",
                    Confirm = "Potwierdz zmiane",
                    OnSuccess = "alert('Pomyslnie zmieniono')",
                    UpdateTargetId = "Spotk"
                }))
                {
                    @Html.AntiForgeryToken()
                    <span style="color: red;">
                        @Html.ValidationSummary(true)
                    </span>


                    @Html.HiddenFor(a => obiekt.ObiektSportowy)
                    @Html.HiddenFor(a => obiekt.ObiektSportowyID)
                    @Html.HiddenFor(a => obiekt.UserId)
                    @Html.HiddenFor(a => obiekt.SpotkanieID)
                    @Html.HiddenFor(a => obiekt.ApplicationUsers)
                    @Html.HiddenFor(a => obiekt.DataDodania)

                    <div class="card border-white h-100">
                        <div class="card-body">
                            <h4 class="card-title">
                                @Html.TextBoxFor(a => obiekt.DataSpotkania)
                                                        @Html.ValidationMessageFor(o => obiekt.GodzinaRozpoczecia)
                                                    </h4>
                            <h6 class="text-muted card-subtitle mb-2">
                                @Html.TextBoxFor(a => obiekt.GodzinaRozpoczecia)
                                @Html.ValidationMessageFor(o => obiekt.GodzinaRozpoczecia)
                                |
                                @Html.TextBoxFor(a => obiekt.GodzinaZakonczenia)
                                @Html.ValidationMessageFor(o => obiekt.GodzinaRozpoczecia)
                            </h6>
                            <p class="card-text">@Html.TextBoxFor(a => obiekt.OpisSpotkania)</p>
                        </div>
                        <ul class="list-group list-group-flush" style="margin-top:35px;">
                            <li class="list-group-item">
                                Cena: @Html.TextBoxFor(a => obiekt.Cena)
                                @Html.ValidationMessageFor(o => obiekt.Cena)
                            </li>
                            <li class="list-group-item">
                                @obiekt.LiczbaMiejscZajetych
                                @Html.ValidationMessageFor(o => obiekt.LiczbaMiejscZajetych)
                                /@Html.TextBoxFor(a => obiekt.ObiektSportowy.MaksymalnaLiczbaMiejsc)
                            </li>
                        </ul>
                    </div>
                    <button type="submit">Zmodyfikuj</button>
                }
                <ul class="list-group list-group-flush" style="margin-top:35px;">
                    @if (obiekt.ApplicationUsers.Count > 0)
                    {
                        <h4><strong>Dołączyli:</strong></h4>
                        foreach (var us in obiekt.ApplicationUsers)
                        {
                            <span id="@us.UserName" name="@obiekt.SpotkanieID">
                                <li id="4">@us.UserName</li>
                                <button class="btn btn-danger" onclick="Usun(this)" id="Usun">Usuń ze spotkania</button>
                            </span>
                        }
                    }
                    else if (obiekt.ApplicationUsers.Count <= 0)
                    {
                        <h4 style="text-align:center;"><strong>NIKT JESZCZE NIE DOŁĄCZYŁ DO SPOTKANIA!</strong></h4>
                    }
                </ul>
            </div>
        </div>
        <hr />
    }
</div>

ZagrajZNami/ZagrajZNami/Views/Admin/_UzytkownicyList.cshtml
@model List<ZagrajZNami.Models.ApplicationUser>

@{
    /**/

    Layout = null;
}


<span>
    <h1> @ViewBag.Innfo</h1>
</span>

<div class="row" style="margin-top: 100px;">
    @foreach (var obiekt in Model)
    {
        if(obiekt.UserName == "admin@zagrajznami.pl" || obiekt.Email == "admin@zagrajznami.pl")
        {
            continue;
        }
    <div class="col-lg-4 col-sm-3">
        @using (Ajax.BeginForm("Uzytkownicy", obiekt.DaneUzytkownika, new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            Confirm = "Potwierdz zmiane",
            OnSuccess = "alert('Pomyslnie zmieniono')",
            UpdateTargetId = "Users",
        }))
        {
            @Html.AntiForgeryToken()
            <div class="card" style="width: 30rem;">
                <div class="card-header">
                    <strong style="color:red;"> @obiekt.UserName</strong>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Potwierdzony Email  @if (obiekt.EmailConfirmed)
                        {
                            
                        <strong>Tak</strong> }
                    else
                    { <strong>Nie</strong>}
</li>
                    <li class="list-group-item">Liczba nieudanych prób <strong>[@obiekt.AccessFailedCount]</strong></li>
                    @if (obiekt.DaneUzytkownika != null)
                    {
                        <li class="list-group-item">
                            Imie <strong>[@obiekt.DaneUzytkownika.Imie]</strong>
                            <input type="text" name="Imie" />
                        </li>
                        <li class="list-group-item">
                            Nazwisko <strong>[@obiekt.DaneUzytkownika.Nazwisko]</strong>
                            <input type="text" name="Nazwisko" />
                        </li>
                        <li class="list-group-item">
                            Adres <strong>[@obiekt.DaneUzytkownika.Adres]</strong>
                            <input type="text" name="Adres" />
                        </li>
                        <li class="list-group-item">
                            Miasto <strong>[@obiekt.DaneUzytkownika.Miasto]</strong>
                            <input type="text" name="Miasto" />
                        </li>
                        <li class="list-group-item">
                            KodPocztowy <strong>[@obiekt.DaneUzytkownika.KodPocztowy]</strong>
                            <input type="text" name="KodPocztowy" />
                        </li>
                        <li class="list-group-item">
                            Telefon <strong>[@obiekt.DaneUzytkownika.Telefon]</strong>
                            <input type="text" name="Telefon" />
                        </li>
                    }
                </ul>
                <button class="btn btn-warning" type="submit" onclick="Usun(this)" id="Usun">Zmieńs</button>
            </div>
        }
        <button class="btn btn-danger" onclick="Usun(this)" id="@obiekt.Id">Usuń ze spotkania</button>
    </div>
    }
</div>